### ISSUE TITLE
USB camera

### ISSUE THREAD

**Issue by goggledefogger** [waveform80/pistreaming#8] opened 2016-03-16 04:33 UTC
I really like the idea of your cross-platform streaming solution, but haven't been able to get it to work yet. When I run server.py I get the error that says "Camera is not enabled", but I think that's because I'm not using the Pi camera (I'm using a Microsoft USB webcam) which is incompatible with the picamera python module.

Is there any way to get this to work with a USB webcam?

**Comment by waveform80** [comment] 2016-03-16 08:38
Duplicate of #7

**Closed as completed by waveform80** 2016-03-16 08:38 UTC
Labels: duplicate
